#+LATEX_CLASS: article
#+OPTIONS: author:nil toc:nil num:nil
#+LaTeX_CLASS_OPTIONS: [a4paper,11pt]
#+LaTeX_HEADER: \usepackage[margin=1.2in]{geometry}
#+LaTeX_HEADER: \usepackage[]{keystroke}
#+LaTeX_HEADER: \pagenumbering{gobble}
#+LATEX_HEADER: \usepackage[ngerman]{babel}
#+LANGUAGE: de
#+TITLE:
#+DATE: 


TODO: Add predicates and actions to domain,
init and goal to problem and sequence of actions to plan
file://../img/pddl-workflow.pdf
The \textsc{pddl} workflow.
domain.pddl and problem.pddl represent typical planning specification
files, with the standard file extension .pddl \textsc{pddl} is
extensive and not all parts are mandatory components of task
specifications.

* Instruktionen (Aufgabe 1 & Aufgabe 2)

Auf der nächsten Seite findest du eine kurze Beschreibung einer
Hierarchie. Deine Aufgabe ist es, eine Domäne soweit im Editor Sublime
Text zu erstellen, bis diese Typenhierarchie repräsentiert ist. D.h.
du musst dich nicht um Prädikate und auch nicht um Aktionen kümmern.
Du darfst die Domäne nennen wie du möchtest, der Name sollte aber
aussagekräftig sein und sich auf den Inhalt beziehen. Als Requirement
ist nur typing wichtig. Bevor du beginnst, solltest du dir zunächst
ein Diagramm der Hierarchie zeichnen. Hierfür ist auch auf der
nächsten Seite Platz. Es besteht kein Zeitdruck, aber versuche nicht
zu trödeln. Du darfst außerdem jederzeit auf das Tutorial
zurückgreifen.
/Wichtig/: Nicht du wirst getestet, sondern das Programm.
Alle Schwierigkeiten die du hast, geben Aufschluss darüber, was an dem
Programm noch nicht optimal ist. Damit detailliertere Einblicke in die
Benutzungserfahrung möglich sind, solltest du alle deine
Gedanken/Gefühle verbalisieren während du der Aufgabe nachgehst.
Versuch bei jedem Schritt zu erzählen was du gerade machst, warum du
machst was du machst und wie es dir dabei geht.

Damit dir das Ganze leichter fällt, gibt es zwei Tools die dir beim
Erstellen helfen sollen. Zunächst gibt es das Tool „snippets“ das
automatisch Code-Schnipsel generiert. Du musst also nach dem Öffnen
des Editors nur domain eingeben und auf Return drücken, und das
gesamte Gerüst für eine Domäne (ähnlich wie zu Beginn des Tutorials
vorgestellt) wird erstellt. Dieses muss dann nur noch ausgefüllt
werden. Als zweites Tool steht dir ein UML-Generator zur Verfügung.
Dieser erlaubt es dir, während du die Typenhierarchie aufbaust, zu
kontrollieren ob diese auch deinen Vorstellungen entspricht. Hierzu
kannst du jederzeit, während du die Typen erweiterst auf F7 drücken, um
ein Pop-up mit dem UML-Diagramm deiner bisher erstellten Hierarchie
aufzurufen.

Der Editor Sublime Text ist bereits geöffnet. Du findest ihn minimiert
in der Taskleiste, neben dem Tutorial. Bitte schließe keines der
Fenster. Solltest du im Moment noch Fragen haben, zögere bitte nicht
den Versuchsleiter zu fragen. Sobald du mit einer Aufgabe fertig bist,
wende dich bitte an den Versuchsleiter.


\newpage


* Aufgabe 1

Bitte setze folgende Hierarchie in deiner PDDL-Domäne um:

#+BEGIN_QUOTE
In Programmiersprachen gibt es verschiedene generische Typen. Zum
einen wären da die boolschen Werte oder booleans, dann gibt es noch
numbers und flexibles. Die numbers lassen sich wieder unterteilen in
integers und inexacts und analog gibt es zwei Untergruppen von
flexibles: die characters und void. Integers können entweder signed
oder unsigned sein, wobei Beispiele für signed integers byte, short
und long wären, und Beispiele für unsigned könnten entsprechend ubyte,
ushort und ulong heißen. Die inexacts können wieder entweder floats
sein oder complexfloats. Floats können singles oder longfloats sein
und complexfloats können entweder csingles oder clongfloats sein.
#+END_QUOTE



\newpage

* Aufgabe 2

Bitte setze folgende Hierarchie in deiner PDDL-Domäne um:

#+BEGIN_QUOTE
Ein Supermarkt besteht aus verschiedenen Menschen, verschiedenen
Produkten, verschiedenen Einrichtungsgegenständen und einem Lager.
Zumeist gibt es Kassierer, Manager, Verkäufer, Putzpersonal und
Lagerarbeiter. Außerdem gibt es auch noch Lieferanten. Diese liefern
die Produkten zu denen Obst, Gemüse, Fleisch, Käse und Backwaren
zählen. Obst lässt sich wiederum in Äpfel und Birnen unterteilen. Die
Produkte befinden sich auf Regalen. Neben Regalen gibt es Theken an
denen das Fleisch und der Käse verkauft wird. Auch findet man Kassen
im Supermarkt an denen die Kassierer sitzen und Stühle auf denen sie
sitzen. Die Einkaufswägen und –körbe zählen wir jetzt auch einmal zu
den Einrichtungsgegenständen.
#+END_QUOTE


